//! Shared i18n traits and locale definitions
//!
//! This crate provides the `Locale` enum and `Translatable` trait
//! used by both backend (API/handlers/exports) and frontend (Leptos).
//!
//! Translation keys are defined as a generated `Msg` enum in `translation.rs`,
//! produced at build time by `crates/i18n-codegen/build.rs` from YAML sources.

use serde::{Deserialize, Serialize};

/// Supported application locales.
///
/// Stored in order of preference — first is the default.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, PartialOrd, Ord, Default,
)]
pub enum Locale {
    #[default]
    De,
    En,
    Es,
    Fr,
    Pt,
    It,
    Pl,
    Ro,
    Uk,
    Nl,
}

impl Locale {
    /// All supported locales in preference order.
    pub const ALL: &'static [Locale] = &[
        Locale::De,
        Locale::En,
        Locale::Es,
        Locale::Fr,
        Locale::Pt,
        Locale::It,
        Locale::Pl,
        Locale::Ro,
        Locale::Uk,
        Locale::Nl,
    ];

    /// Returns the ISO 639-1 two-letter code (e.g. "de", "en").
    pub const fn code(&self) -> &'static str {
        match self {
            Locale::De => "de",
            Locale::En => "en",
            Locale::Es => "es",
            Locale::Fr => "fr",
            Locale::Pt => "pt",
            Locale::It => "it",
            Locale::Pl => "pl",
            Locale::Ro => "ro",
            Locale::Uk => "uk",
            Locale::Nl => "nl",
        }
    }
}

impl std::fmt::Display for Locale {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.code())
    }
}

/// Parse a locale from a string like "de", "de-DE", "de_DE", "en-US".
/// Falls back to the given default.
impl std::str::FromStr for Locale {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let code = s.split(['-', '_']).next().unwrap_or("");
        match code.to_ascii_lowercase().as_str() {
            "de" => Ok(Locale::De),
            "en" => Ok(Locale::En),
            "es" => Ok(Locale::Es),
            "fr" => Ok(Locale::Fr),
            "pt" => Ok(Locale::Pt),
            "it" => Ok(Locale::It),
            "pl" => Ok(Locale::Pl),
            "ro" => Ok(Locale::Ro),
            "uk" => Ok(Locale::Uk),
            "nl" => Ok(Locale::Nl),
            _ => Err(()),
        }
    }
}

/// Trait for any message key that can be translated.
///
/// Implemented by the generated `Msg` enum in `translation.rs` (build time).
pub trait Translatable {
    fn tr(&self, locale: Locale) -> &'static str;
}

/// Helper: translate a slice of keys and collect into owned strings.
#[inline]
pub fn translate_all(keys: &[impl Translatable], locale: Locale) -> Vec<String> {
    keys.iter().map(|k| k.tr(locale).to_string()).collect()
}

// Include the generated Msg enum + Translatable impl.
// Generated by build.rs in `crates/i18n-shared`.
include!(concat!(env!("OUT_DIR"), "/translation.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_msg_translatable() {
        // Key that exists in app.yml
        let key = Msg::YES;
        let de = key.tr(Locale::De);
        let en = key.tr(Locale::En);
        assert_eq!(de, "Ja", "German translation for YES should be 'Ja'");
        assert_eq!(en, "Yes", "English translation for YES should be 'Yes'");
    }

    #[test]
    fn test_locale_code() {
        assert_eq!(Locale::De.code(), "de");
        assert_eq!(Locale::En.code(), "en");
        assert_eq!(Locale::Uk.code(), "uk");
    }

    #[test]
    fn test_locale_from_str() {
        use std::str::FromStr;
        assert_eq!(Locale::from_str("de"), Ok(Locale::De));
        assert_eq!(Locale::from_str("de-DE"), Ok(Locale::De));
        assert_eq!(Locale::from_str("DE_de"), Ok(Locale::De));
        assert_eq!(Locale::from_str("invalid"), Err(()));
    }

    #[test]
    fn test_locale_default() {
        assert_eq!(Locale::default(), Locale::De);
    }

    #[test]
    fn test_msg_key() {
        assert_eq!(Msg::YES.key(), "YES");
    }
}
