[package]
name = "agrocore-messaging"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
async-nats.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
agrocore-logging = { path = "../logging", features = ["dev-console"] }
failsafe = "1.2"
anyhow.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true
agrocore-domain = { path = "../domain" }
agrocore-shared = { path = "../shared" }
bytes = "1.0"
utoipa.workspace = true
validator.workspace = true
rumqttc.workspace = true

futures-util = "0.3.32"
[features]
mocks = []
