[package]
name = "agrocore-messaging"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
async-nats.workspace = true
serde.workspace = true
serde_json.workspace = true
agrocore-logging = { path = "../logging", features = ["dev-console"] }
failsafe = "1.2"
anyhow.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true
agrocore-domain = { path = "../domain" }
agrocore-shared = { path = "../shared" }
bytes = "1.0"
utoipa.workspace = true
validator.workspace = true
rumqttc.workspace = true

futures-util = "0.3.32"
async-trait = "0.1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "multipart"] }
lettre = { version = "0.11", default-features = false, features = ["builder", "smtp-transport", "tokio1-rustls-tls", "rustls-tls"] }

base64 = "0.22"
sha2 = "0.10"
hmac = "0.12"
tokio = { workspace = true, features = ["rt-multi-thread", "process", "macros", "time", "sync", "signal"] }

actix-web = "4"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_yaml = "0.9"

[features]
mocks = []
