[package]
name = "agrocore-infrastructure"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
agrocore-domain = { path = "../domain" }
agrocore-shared = { path = "../shared" }
sqlx = { workspace = true }
geozero = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
chrono = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
jsonwebtoken = { workspace = true }
argon2 = { workspace = true }

[features]
default = []

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }