-- Migration to update sites and orders table with missing columns
ALTER TABLE sites 
ADD COLUMN IF NOT EXISTS plots JSONB NOT NULL DEFAULT '[]'::JSONB,
ADD COLUMN IF NOT EXISTS row_config JSONB,
ADD COLUMN IF NOT EXISTS bbch_stage JSONB,
ADD COLUMN IF NOT EXISTS planted_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS cleared_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS soil_type TEXT,
ADD COLUMN IF NOT EXISTS slope DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS slope_facing TEXT,
ADD COLUMN IF NOT EXISTS altitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS organic BOOLEAN,
ADD COLUMN IF NOT EXISTS organic_eligible BOOLEAN,
ADD COLUMN IF NOT EXISTS sigpac_data JSONB,
ADD COLUMN IF NOT EXISTS regepac_id TEXT,
ADD COLUMN IF NOT EXISTS properties JSONB DEFAULT '[]'::JSONB,
ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::JSONB,
ADD COLUMN IF NOT EXISTS note1 TEXT,
ADD COLUMN IF NOT EXISTS note2 TEXT;

-- Update orders table
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS site_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
ADD COLUMN IF NOT EXISTS assigned_worker_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
ADD COLUMN IF NOT EXISTS last_completed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS execution_policy JSONB,
ADD COLUMN IF NOT EXISTS automation_state JSONB,
ADD COLUMN IF NOT EXISTS articles JSONB,
ADD COLUMN IF NOT EXISTS quantities JSONB,
ADD COLUMN IF NOT EXISTS results TEXT,
ADD COLUMN IF NOT EXISTS weather JSONB,
ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}'::JSONB,
ADD COLUMN IF NOT EXISTS parent_order_id UUID,
ADD COLUMN IF NOT EXISTS workflow_config JSONB,
ADD COLUMN IF NOT EXISTS cost_center_id UUID,
ADD COLUMN IF NOT EXISTS created_by UUID,
ADD COLUMN IF NOT EXISTS updated_by UUID;

-- Indexing for some of the new columns might be useful
CREATE INDEX IF NOT EXISTS idx_sites_regepac_id ON sites(regepac_id);
CREATE INDEX IF NOT EXISTS idx_orders_parent_order_id ON orders(parent_order_id);
