-- Migration to add missing columns to task_data table
ALTER TABLE task_data
ADD COLUMN IF NOT EXISTS order_id UUID REFERENCES orders(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS site_id UUID REFERENCES sites(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS paused_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS resume_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS duration_minutes INTEGER,
ADD COLUMN IF NOT EXISTS machine_id UUID,
ADD COLUMN IF NOT EXISTS machine_hours DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS cost_center_id UUID,
ADD COLUMN IF NOT EXISTS area_covered DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS materials_used JSONB,
ADD COLUMN IF NOT EXISTS observations TEXT,
ADD COLUMN IF NOT EXISTS gps_track JSONB,
ADD COLUMN IF NOT EXISTS photo_urls JSONB;

-- Add index for order_id
CREATE INDEX IF NOT EXISTS idx_task_data_order ON task_data(order_id);
CREATE INDEX IF NOT EXISTS idx_task_data_site ON task_data(site_id);