//! Build script for `agrocore-i18n-shared`
//!
//! Reads `crates/admin-ui/locales/app.yml` and generates
//! `translation.rs` in `OUT_DIR` containing:
//!   - A `Msg` enum with one variant per YAML top-level key
//!   - A `Translatable` impl mapping each variant + locale to a `&'static str`

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Locate the YAML source relative to the i18n-shared crate.
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let yaml_path = manifest_dir
        .parent()
        .unwrap()
        .join("admin-ui/locales/app.yml");

    println!("cargo:rerun-if-changed={}", yaml_path.display());

    let yaml_content = fs::read_to_string(&yaml_path)
        .unwrap_or_else(|e| panic!("Failed to read i18n YAML at {}: {}", yaml_path.display(), e));

    // Parse the YAML into nested BTreeMap<String, BTreeMap<String, String>>.
    // Some top-level keys (like _version: 2) are scalars, not maps — filter them out.
    let parsed: BTreeMap<String, serde_yaml::Value> = serde_yaml::from_str(&yaml_content)
        .unwrap_or_else(|e| panic!("Failed to parse YAML at {}: {}", yaml_path.display(), e));

    let mut entries: Vec<(String, BTreeMap<String, String>)> = Vec::new();
    for (key, value) in &parsed {
        if let serde_yaml::Value::Mapping(map) = value {
            let lang_map: Result<BTreeMap<String, String>, _> = map
                .iter()
                .map(|(k, v)| {
                    let key_str = k
                        .as_str()
                        .ok_or_else(|| format!("Non-string key in {}: {:?}", key, k));
                    let val_str = v
                        .as_str()
                        .ok_or_else(|| format!("Non-string value in {}: {:?}", key, v));
                    key_str.and_then(|k| val_str.map(|v| (k.to_string(), v.to_string())))
                })
                .collect();
            match lang_map {
                Ok(m) => entries.push((key.clone(), m)),
                Err(e) => eprintln!("cargo:warning=[i18n-codegen] Skipping key {}: {}", key, e),
            }
        }
    }
    entries.sort_by(|(a, _), (b, _)| a.cmp(b));

    let mut enum_variants: Vec<String> = Vec::new();
    let mut match_arms: Vec<String> = Vec::new();

    for (raw_key, langs) in &entries {
        let variant = to_screaming_snake(raw_key);
        if variant.is_empty() || variant.starts_with('_') {
            continue; // skip internal keys like _version
        }
        enum_variants.push(variant.clone());

        for (lang_code, text) in langs {
            let locale = lang_code_to_locale(lang_code);
            let escaped = escape_rust_string(text);
            match_arms.push(format!(
                "            (Msg::{variant}, Locale::{locale}) => \"{escaped}\""
            ));
        }
    }

    let enum_body = enum_variants
        .iter()
        .map(|v| format!("    {v},"))
        .collect::<Vec<_>>()
        .join("\n");

    let match_body = match_arms.join(",\n");
    let default_arms = generate_default_arms(&entries);
    let key_arms = generate_key_arms(&enum_variants);

    let generated = format!(
        r#"// ! AUTO-GENERATED by build.rs — DO NOT EDIT BY HAND.
// ! Source: crates/admin-ui/locales/app.yml

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(clippy::too_many_lines)]
#[allow(non_camel_case_types)]
pub enum Msg {{
{enum_body}
}}

impl Translatable for Msg {{
    #[allow(unreachable_patterns)]
    fn tr(&self, locale: Locale) -> &'static str {{
        match (self, locale) {{
{match_body},
            _ => self.default_text(),
        }}
    }}
}}

impl Msg {{
    /// Fallback text in the default locale (De).
    fn default_text(&self) -> &'static str {{
        match self {{
{default_arms}
        }}
    }}

    pub const fn key(self) -> &'static str {{
        match self {{
{key_arms}
        }}
    }}
}}
"#,
        enum_body = enum_body,
        match_body = match_body,
        default_arms = default_arms,
        key_arms = key_arms,
    );

    fs::write(out_dir.join("translation.rs"), generated).expect("Failed to write translation.rs");

    println!(
        "cargo:warning=[i18n-codegen] Generated Msg enum with {} variants",
        enum_variants.len()
    );
}

fn generate_default_arms(entries: &[(String, BTreeMap<String, String>)]) -> String {
    entries
        .iter()
        .filter_map(|(raw_key, langs)| {
            let variant = to_screaming_snake(raw_key);
            if variant.is_empty() || variant.starts_with('_') {
                return None;
            }
            let de_text = langs
                .get("de")
                .or_else(|| langs.get("en"))
                .map(|s| escape_rust_string(s.as_str()))
                .unwrap_or_default();
            Some(format!("            Msg::{variant} => \"{de_text}\""))
        })
        .collect::<Vec<_>>()
        .join(",\n")
}

fn generate_key_arms(variants: &[String]) -> String {
    variants
        .iter()
        .map(|v| format!("            Msg::{v} => \"{v}\""))
        .collect::<Vec<_>>()
        .join(",\n")
}

fn to_screaming_snake(key: &str) -> String {
    key.to_uppercase().replace('-', "_")
}

fn lang_code_to_locale(lang_code: &str) -> &'static str {
    match lang_code {
        "de" => "De",
        "en" => "En",
        "es" => "Es",
        "fr" => "Fr",
        "pt" => "Pt",
        "it" => "It",
        "pl" => "Pl",
        "ro" => "Ro",
        "uk" => "Uk",
        "nl" => "Nl",
        _ => "De",
    }
}

fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
        .replace('"', "\\\"")
}
