[package]
name = "agrocore-domain"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
agrocore-shared = { path = "../shared" }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras", "uuid", "chrono"] }
chrono = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }
geo = { workspace = true }
mockall = { workspace = true }
sqlx = { workspace = true }
geozero = { workspace = true }
strum = { version = "0.26", features = ["derive"] }