[package]
name = "agrocore-domain"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
agrocore-shared = { path = "../shared", features = ["sqlx"] }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras", "uuid", "chrono"] }
chrono = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }
geo = { workspace = true }
mockall = { workspace = true, optional = true }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "macros", "uuid", "chrono", "ipnetwork", "bigdecimal", "json"], optional = true }
geozero = { workspace = true }
strum = { version = "0.28", features = ["derive"] }

[features]
default = ["sqlx"]
sqlx = ["dep:sqlx", "agrocore-shared/sqlx"]
mocks = ["dep:mockall"]
depreciation = []
